# Generated by Django 2.2.4 on 2019-08-26 22:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carta',
            name='sera_visto_em',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
